package main

import (
	"fmt"
	"strings"
)

// ─────────────────────────────────────────────────────────────────────────────
//  Known C stdlib functions — do NOT re-declare these as extern
//  (they're already declared by the #include headers)
// ─────────────────────────────────────────────────────────────────────────────

var knownCFuncs = map[string]bool{
	// stdio.h
	"printf": true, "fprintf": true, "sprintf": true, "snprintf": true,
	"scanf":  true, "fscanf":  true, "sscanf":  true,
	"fopen":  true, "fclose":  true, "fread":   true, "fwrite":  true,
	"fgets":  true, "fputs":   true, "feof":    true, "fflush":  true,
	"puts":   true, "getchar": true, "putchar": true, "getc":    true, "putc": true,
	"perror": true,
	// stdlib.h
	"malloc":  true, "calloc":  true, "realloc": true, "free":    true,
	"exit":    true, "abort":   true, "atoi":    true, "atof":    true, "atol": true,
	"rand":    true, "srand":   true, "abs":     true, "labs":    true,
	"strtol":  true, "strtod":  true, "qsort":   true, "bsearch": true,
	// string.h
	"strlen":  true, "strcpy":  true, "strncpy": true, "strcat":  true, "strncat": true,
	"strcmp":  true, "strncmp": true, "strchr":  true, "strrchr": true, "strstr": true,
	"memcpy":  true, "memmove": true, "memset":  true, "memcmp":  true,
	// math.h
	"sqrt": true, "pow":   true, "fabs": true, "floor": true, "ceil": true,
	"sin":  true, "cos":   true, "tan":  true, "asin":  true, "acos": true, "atan": true,
	"atan2":true, "exp":   true, "log":  true, "log2":  true, "log10":true,
	"fmod": true, "round": true, "trunc":true,
	// ctype.h
	"isalpha":true, "isdigit":true, "isspace":true, "isupper":true, "islower":true,
	"toupper":true, "tolower":true,
	// time.h
	"time":  true, "clock": true, "difftime": true,
}

// ─────────────────────────────────────────────────────────────────────────────
//  Emitter
// ─────────────────────────────────────────────────────────────────────────────

type Emitter struct {
	sb     strings.Builder
	indent int
}

func Emit(prog *Program) string {
	e := &Emitter{}
	e.emitProgram(prog)
	return e.sb.String()
}

func (e *Emitter) w(s string) { e.sb.WriteString(s) }
func (e *Emitter) ln(f string, args ...any) {
	e.sb.WriteString(strings.Repeat("    ", e.indent))
	if len(args) > 0 {
		e.sb.WriteString(fmt.Sprintf(f, args...))
	} else {
		e.sb.WriteString(f)
	}
	e.sb.WriteByte('\n')
}

func (e *Emitter) emitProgram(prog *Program) {
	e.ln("/* generated by zxc — do not edit */")
	e.ln("#include <stdio.h>")
	e.ln("#include <stdlib.h>")
	e.ln("#include <string.h>")
	e.ln("#include <math.h>")
	e.ln("#include <stdbool.h>")
	e.ln("")

	// user imports
	for _, imp := range prog.Imports {
		e.ln("#include <%s>", imp.Path)
	}
	if len(prog.Imports) > 0 { e.ln("") }

	// struct declarations
	for _, s := range prog.Structs {
		e.emitStruct(s)
	}

	// extern function prototypes —— SKIP any that are known C stdlib funcs
	// because they are already declared via the #include headers above
	externEmitted := 0
	for _, ext := range prog.Externs {
		if knownCFuncs[ext.Name] {
			continue // already declared by header
		}
		e.emitExternProto(ext)
		externEmitted++
	}
	if externEmitted > 0 { e.ln("") }

	// forward-declare user functions
	fwdEmitted := 0
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok && fn.Name != "main" {
			e.emitFnProto(fn)
			fwdEmitted++
		}
	}
	if fwdEmitted > 0 { e.ln("") }

	// collect top-level statements vs function declarations
	var mainStmts []Node
	var fnDecls   []*FnDecl
	var hasUserMain bool
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok {
			fnDecls = append(fnDecls, fn)
			if fn.Name == "main" { hasUserMain = true }
		} else {
			mainStmts = append(mainStmts, stmt)
		}
	}

	// emit function bodies
	for _, fn := range fnDecls {
		e.emitFnFull(fn)
		e.ln("")
	}

	// wrap top-level stmts in main() if no user-defined main
	if !hasUserMain {
		e.ln("int main(int argc, char **argv) {")
		e.indent++
		for _, s := range mainStmts {
			e.emitStmt(s)
		}
		e.ln("return 0;")
		e.indent--
		e.ln("}")
	}
}

// ── Types → C ─────────────────────────────────────────────────────────────────

func cType(t *ZXType) string {
	if t == nil { return "void" }
	switch t.Kind {
	case TyInt:    return "long long"
	case TyFloat:  return "double"
	case TyBool:   return "int"
	case TyStr:    return "const char*"
	case TyChar:   return "char"
	case TyVoid:   return "void"
	case TyPtr:
		if t.PtrElem != nil { return cType(t.PtrElem) + "*" }
		return "void*"
	case TyArray:
		if t.ArrElem != nil { return cType(t.ArrElem) }
		return "void*"
	case TyStruct: return t.Name
	default:       return "void"
	}
}

// For declarations that need the array size suffix: int arr[10]
func cTypeDecl(t *ZXType, name string) string {
	if t != nil && t.Kind == TyArray {
		size := ""
		if t.ArrSize > 0 { size = fmt.Sprintf("%d", t.ArrSize) }
		return fmt.Sprintf("%s %s[%s]", cType(t.ArrElem), name, size)
	}
	return fmt.Sprintf("%s %s", cType(t), name)
}

// ── Structs ───────────────────────────────────────────────────────────────────

func (e *Emitter) emitStruct(s *StructDecl) {
	e.ln("typedef struct %s {", s.Name)
	e.indent++
	for _, f := range s.Fields {
		e.ln("%s;", cTypeDecl(f.Type, f.Name))
	}
	e.indent--
	e.ln("} %s;", s.Name)
	e.ln("")
}

// ── Extern proto ──────────────────────────────────────────────────────────────

func (e *Emitter) emitExternProto(ext *ExternDecl) {
	params := buildParamStr(ext.Params, ext.Variadic)
	e.ln("extern %s %s(%s);", cType(ext.RetType), ext.Name, params)
}

// ── Function proto ────────────────────────────────────────────────────────────

func (e *Emitter) emitFnProto(fn *FnDecl) {
	params := buildParamStr(fn.Params, fn.Variadic)
	e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, params)
}

func buildParamStr(params []Param, variadic bool) string {
	if len(params) == 0 {
		if variadic { return "..." }
		return "void"
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = cTypeDecl(p.Type, p.Name)
	}
	if variadic { parts = append(parts, "...") }
	return strings.Join(parts, ", ")
}

// ── Function full definition ──────────────────────────────────────────────────

func (e *Emitter) emitFnFull(fn *FnDecl) {
	var sig string
	if fn.Name == "main" {
		sig = "int main(int argc, char **argv)"
	} else {
		params := buildParamStr(fn.Params, fn.Variadic)
		sig = fmt.Sprintf("%s %s(%s)", cType(fn.RetType), fn.Name, params)
	}
	e.ln("%s {", sig)
	e.indent++
	for _, s := range fn.Body.Stmts {
		e.emitStmt(s)
	}
	if fn.Name == "main" {
		e.ln("return 0;")
	}
	e.indent--
	e.ln("}")
}

// ── Statements ────────────────────────────────────────────────────────────────

func (e *Emitter) emitStmt(n Node) {
	if n == nil { return }
	switch s := n.(type) {
	case *VarDecl:      e.emitVarDecl(s)
	case *ReturnStmt:   e.emitReturn(s)
	case *IfStmt:       e.emitIf(s)
	case *WhileStmt:    e.emitWhile(s)
	case *ForRangeStmt: e.emitForRange(s)
	case *AssignStmt:   e.emitAssign(s)
	case *ExprStmt:
		expr := e.emitExpr(s.Expr)
		e.ln("%s;", expr)
	case *PrintStmt:    e.emitPrint(s)
	case *ExitStmt:
		code := e.emitExpr(s.Code)
		e.ln("exit((int)(%s));", code)
	case *BreakStmt:    e.ln("break;")
	case *ContinueStmt: e.ln("continue;")
	case *FnDecl:       e.emitFnFull(s)
	case *Block:
		e.ln("{")
		e.indent++
		for _, st := range s.Stmts { e.emitStmt(st) }
		e.indent--
		e.ln("}")
	}
}

func (e *Emitter) emitVarDecl(v *VarDecl) {
	typ := v.ResolvedType
	if typ == nil { typ = v.VarType }
	if typ == nil { typ = TypInt }

	prefix := ""
	if v.IsConst { prefix = "const " }

	if v.Init != nil {
		init := e.emitExpr(v.Init)
		if typ.Kind == TyArray {
			// arrays: int arr[10] = {1, 2, 3}
			e.ln("%s%s = %s;", prefix, cTypeDecl(typ, v.Name), init)
		} else {
			e.ln("%s%s = %s;", prefix, cTypeDecl(typ, v.Name), init)
		}
	} else {
		e.ln("%s%s;", prefix, cTypeDecl(typ, v.Name))
	}
}

func (e *Emitter) emitReturn(r *ReturnStmt) {
	if r.Value == nil {
		e.ln("return;")
	} else {
		e.ln("return %s;", e.emitExpr(r.Value))
	}
}

func (e *Emitter) emitIf(s *IfStmt) {
	e.ln("if (%s) {", e.emitExpr(s.Cond))
	e.indent++
	for _, st := range s.Then.Stmts { e.emitStmt(st) }
	e.indent--
	for _, el := range s.Elifs {
		e.ln("} else if (%s) {", e.emitExpr(el.Cond))
		e.indent++
		for _, st := range el.Body.Stmts { e.emitStmt(st) }
		e.indent--
	}
	if s.Else != nil {
		e.ln("} else {")
		e.indent++
		for _, st := range s.Else.Stmts { e.emitStmt(st) }
		e.indent--
	}
	e.ln("}")
}

func (e *Emitter) emitWhile(s *WhileStmt) {
	e.ln("while (%s) {", e.emitExpr(s.Cond))
	e.indent++
	for _, st := range s.Body.Stmts { e.emitStmt(st) }
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitForRange(s *ForRangeStmt) {
	from := e.emitExpr(s.From)
	to   := e.emitExpr(s.To)
	e.ln("for (long long %s = %s; %s < %s; %s++) {", s.Var, from, s.Var, to, s.Var)
	e.indent++
	for _, st := range s.Body.Stmts { e.emitStmt(st) }
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitAssign(s *AssignStmt) {
	e.ln("%s %s %s;", e.emitExpr(s.LHS), s.Op, e.emitExpr(s.Value))
}

func (e *Emitter) emitPrint(s *PrintStmt) {
	if len(s.Args) == 0 {
		if s.Newline { e.ln(`printf("\n");`) }
		return
	}
	var fmts []string
	var args []string
	for _, a := range s.Args {
		typ := exprType(a)
		fmts = append(fmts, fmtFor(typ))
		args = append(args, e.emitExpr(a))
	}
	sep := " "
	if s.Newline { sep = "" }
	fmtStr := strings.Join(fmts, sep)
	if s.Newline { fmtStr += "\\n" }
	e.ln(`printf("%s", %s);`, fmtStr, strings.Join(args, ", "))
}

// ── Expressions ───────────────────────────────────────────────────────────────

func (e *Emitter) emitExpr(n Node) string {
	if n == nil { return "0" }
	switch ex := n.(type) {
	case *IntLit:
		return fmt.Sprintf("%dLL", ex.Val)
	case *FloatLit:
		s := fmt.Sprintf("%g", ex.Val)
		if !strings.Contains(s, ".") && !strings.Contains(s, "e") {
			s += ".0"
		}
		return s
	case *BoolLit:
		if ex.Val { return "1" }
		return "0"
	case *StrLit:
		return cEscapeString(ex.Val)
	case *NilLit:
		return "NULL"
	case *Ident:
		return ex.Name
	case *BinExpr:
		l := e.emitExpr(ex.LHS)
		r := e.emitExpr(ex.RHS)
		return fmt.Sprintf("(%s %s %s)", l, ex.Op, r)
	case *UnaryExpr:
		return fmt.Sprintf("(%s%s)", ex.Op, e.emitExpr(ex.Operand))
	case *CallExpr:
		fn := e.emitExpr(ex.Func)
		var argStrs []string
		for _, a := range ex.Args { argStrs = append(argStrs, e.emitExpr(a)) }
		return fmt.Sprintf("%s(%s)", fn, strings.Join(argStrs, ", "))
	case *IndexExpr:
		return fmt.Sprintf("%s[%s]", e.emitExpr(ex.Obj), e.emitExpr(ex.Idx))
	case *FieldExpr:
		obj := e.emitExpr(ex.Obj)
		// pointer-to-struct: use ->
		objType := exprType(ex.Obj)
		if objType != nil && objType.Kind == TyPtr {
			return fmt.Sprintf("%s->%s", obj, ex.Field)
		}
		return fmt.Sprintf("%s.%s", obj, ex.Field)
	case *CastExpr:
		return fmt.Sprintf("((%s)(%s))", cType(ex.ToType), e.emitExpr(ex.Operand))
	case *AddrExpr:
		if ex.Deref {
			return fmt.Sprintf("(*%s)", e.emitExpr(ex.Operand))
		}
		return fmt.Sprintf("(&%s)", e.emitExpr(ex.Operand))
	case *StructInit:
		var parts []string
		for _, fi := range ex.Fields {
			parts = append(parts, fmt.Sprintf(".%s = %s", fi.Name, e.emitExpr(fi.Value)))
		}
		return fmt.Sprintf("(%s){%s}", ex.Name, strings.Join(parts, ", "))
	case *ArrayLit:
		var parts []string
		for _, el := range ex.Elems { parts = append(parts, e.emitExpr(el)) }
		return fmt.Sprintf("{%s}", strings.Join(parts, ", "))
	case *SizeofExpr:
		return fmt.Sprintf("(long long)sizeof(%s)", cType(ex.Of))
	default:
		return "0"
	}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func fmtFor(t *ZXType) string {
	if t == nil { return "%s" }
	switch t.Kind {
	case TyInt:   return "%lld"
	case TyFloat: return "%g"
	case TyBool:  return "%d"
	case TyStr:   return "%s"
	case TyChar:  return "%c"
	case TyPtr:   return "%p"
	default:      return "%s"
	}
}

func exprType(n Node) *ZXType {
	switch e := n.(type) {
	case *IntLit:    return TypInt
	case *FloatLit:  return TypFloat
	case *BoolLit:   return TypBool
	case *StrLit:    return TypStr
	case *Ident:     return e.Typ
	case *BinExpr:   return e.Typ
	case *UnaryExpr: return e.Typ
	case *CallExpr:  return e.Typ
	case *CastExpr:  return e.Typ
	case *AddrExpr:  return e.Typ
	case *FieldExpr: return e.Typ
	case *IndexExpr: return e.Typ
	case *ArrayLit:  return e.Typ
	case *SizeofExpr:return TypInt
	default:         return TypUnknown
	}
}

// cEscapeString turns a Go string into a C string literal (with quotes)
func cEscapeString(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':  sb.WriteString(`\"`)
		case '\\': sb.WriteString(`\\`)
		case '\n': sb.WriteString(`\n`)
		case '\t': sb.WriteString(`\t`)
		case '\r': sb.WriteString(`\r`)
		case 0:    sb.WriteString(`\0`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
