package main

import (
	"fmt"
	"strings"
)

type Emitter struct {
	sb         strings.Builder
	indent     int
	deferBuf   []string // deferred calls per function
	tmpCounter int
}

func Emit(prog *Program) string {
	e := &Emitter{}
	e.emitProgram(prog)
	return e.sb.String()
}

func (e *Emitter) tmp() string {
	e.tmpCounter++
	return fmt.Sprintf("__zx_tmp%d", e.tmpCounter)
}

func (e *Emitter) ln(f string, args ...any) {
	e.sb.WriteString(strings.Repeat("    ", e.indent))
	if len(args) > 0 {
		e.sb.WriteString(fmt.Sprintf(f, args...))
	} else {
		e.sb.WriteString(f)
	}
	e.sb.WriteByte('\n')
}

func (e *Emitter) raw(s string) { e.sb.WriteString(s); e.sb.WriteByte('\n') }

func (e *Emitter) emitProgram(prog *Program) {
	e.ln("/* generated by zxc v0.2 — do not edit */")
	e.ln("#include <stdio.h>")
	e.ln("#include <stdlib.h>")
	e.ln("#include <string.h>")
	e.ln("#include <math.h>")
	e.ln("#include <stdbool.h>")
	e.ln("#include <errno.h>")
	e.ln("#include <assert.h>")
	e.ln("")

	// user C imports
	for _, imp := range prog.Imports {
		if !imp.IsStd && imp.Path != "" {
			e.ln("#include <%s>", imp.Path)
		}
	}
	// std module extra headers
	for _, h := range prog.StdHeaders() {
		e.ln("#include <%s>", h)
	}
	e.ln("")

	// std helpers (static C functions)
	for _, h := range prog.StdHelpers() {
		e.raw(h)
	}
	if len(prog.StdHelpers()) > 0 {
		e.ln("")
	}

	// input helper
	e.ln("/* built-in input() helper */")
	e.ln("static char __zx_input_buf[4096];")
	e.ln("static const char* __zx_input(const char* prompt) {")
	e.indent++
	e.ln("if (prompt) { fputs(prompt, stdout); fflush(stdout); }")
	e.ln("if (!fgets(__zx_input_buf, sizeof(__zx_input_buf), stdin)) return \"\";")
	e.ln("size_t l = strlen(__zx_input_buf);")
	e.ln("if (l > 0 && __zx_input_buf[l-1] == '\\n') __zx_input_buf[l-1] = '\\0';")
	e.ln("return __zx_input_buf;")
	e.indent--
	e.ln("}")
	e.ln("")

	// cmd capture helper
	e.ln("/* built-in cmd!() capture helper */")
	e.ln("static char __zx_cmd_buf[65536];")
	e.ln("static const char* __zx_capture_cmd(const char* cmd) {")
	e.indent++
	e.ln("FILE* p = popen(cmd, \"r\");")
	e.ln("if (!p) { __zx_cmd_buf[0]='\\0'; return __zx_cmd_buf; }")
	e.ln("size_t total = 0; char tmp[1024];")
	e.ln("while (fgets(tmp, sizeof(tmp), p) && total + strlen(tmp) < sizeof(__zx_cmd_buf)-1) {")
	e.indent++
	e.ln("memcpy(__zx_cmd_buf + total, tmp, strlen(tmp)); total += strlen(tmp);")
	e.indent--
	e.ln("}")
	e.ln("__zx_cmd_buf[total] = '\\0'; pclose(p); return __zx_cmd_buf;")
	e.indent--
	e.ln("}")
	e.ln("")

	// structs
	for _, s := range prog.Structs {
		e.emitStruct(s)
	}

	// externs (skip known C stdlib)
	for _, ext := range prog.Externs {
		if !knownCFuncs[ext.Name] {
			e.ln("extern %s %s(%s);", cType(ext.RetType), ext.Name, buildParamStr(ext.Params, ext.Variadic))
		}
	}

	// forward declarations
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok && fn.Name != "main" {
			e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
		}
	}
	for _, m := range prog.Methods {
		e.ln("%s %s(%s);", cType(m.RetType), m.CName(), methodParamStr(m))
	}
	// forward-declare mod block functions
	for _, mb := range prog.ModBlocks {
		e.emitModBlockProtos(mb)
	}
	e.ln("")

	// function bodies
	var mainStmts []Node
	var fnDecls []*FnDecl
	hasUserMain := false
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok {
			fnDecls = append(fnDecls, fn)
			if fn.Name == "main" {
				hasUserMain = true
			}
		} else {
			mainStmts = append(mainStmts, stmt)
		}
	}
	for _, fn := range fnDecls {
		e.emitFnFull(fn)
		e.ln("")
	}
	for _, m := range prog.Methods {
		e.emitMethodFull(m)
		e.ln("")
	}
	// emit mod block function bodies
	for _, mb := range prog.ModBlocks {
		e.emitModBlockBodies(mb)
	}

	if !hasUserMain {
		e.ln("int main(int argc, char **argv) {")
		e.indent++
		for _, s := range mainStmts {
			e.emitStmt(s)
		}
		e.ln("return 0;")
		e.indent--
		e.ln("}")
	}
}

// emitModBlockProtos forward-declares all functions inside a mod block (recursively).
func (e *Emitter) emitModBlockProtos(mb *ModBlock) {
	for _, s := range mb.Structs {
		e.emitStruct(s)
	}
	for _, fn := range mb.Fns {
		e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
	}
	for _, td := range mb.Tests {
		fn := td.Fn
		e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
	}
	for _, nested := range mb.Mods {
		e.emitModBlockProtos(nested)
	}
}

// emitModBlockBodies emits the full bodies of all mod block functions.
func (e *Emitter) emitModBlockBodies(mb *ModBlock) {
	for _, fn := range mb.Fns {
		e.emitFnFull(fn)
		e.ln("")
	}
	for _, td := range mb.Tests {
		e.emitFnFull(td.Fn)
		e.ln("")
	}
	for _, nested := range mb.Mods {
		e.emitModBlockBodies(nested)
	}
}

func (e *Emitter) emitStruct(s *StructDecl) {
	e.ln("typedef struct %s {", s.Name)
	e.indent++
	for _, f := range s.Fields {
		t := f.Type
		if t == nil {
			t = TypAny
		}
		e.ln("%s;", cTypeDecl(t, f.Name))
	}
	e.indent--
	e.ln("} %s;", s.Name)
	e.ln("")
}

func (e *Emitter) emitFnFull(fn *FnDecl) {
	sig := ""
	if fn.Name == "main" {
		sig = "int main(int argc, char **argv)"
	} else {
		sig = fmt.Sprintf("%s %s(%s)", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
	}
	e.ln("%s {", sig)
	e.indent++
	e.emitBlockStmts(fn.Body)
	if fn.Name == "main" {
		e.ln("return 0;")
	}
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitMethodFull(m *MethodDecl) {
	e.ln("%s %s(%s) {", cType(m.RetType), m.CName(), methodParamStr(m))
	e.indent++
	e.emitBlockStmts(m.Body)
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitBlockStmts(b *Block) {
	if b == nil {
		return
	}
	// collect defers
	var defers []Node
	for _, s := range b.Stmts {
		if ds, ok := s.(*DeferStmt); ok {
			defers = append(defers, ds.Call)
		}
	}
	for _, s := range b.Stmts {
		if _, ok := s.(*DeferStmt); !ok {
			e.emitStmt(s)
		}
	}
	// emit defers in reverse order at end of block
	for i := len(defers) - 1; i >= 0; i-- {
		e.ln("/* deferred */ %s;", e.emitExpr(defers[i]))
	}
}

func (e *Emitter) emitStmt(n Node) {
	if n == nil {
		return
	}
	switch s := n.(type) {
	case *VarDecl:
		e.emitVarDecl(s)
	case *ReturnStmt:
		e.emitReturn(s)
	case *IfStmt:
		e.emitIf(s)
	case *UnlessStmt:
		e.ln("if (!(%s)) {", e.emitExpr(s.Cond))
		e.indent++
		for _, st := range s.Body.Stmts {
			e.emitStmt(st)
		}
		e.indent--
		if s.Else != nil {
			e.ln("} else {")
			e.indent++
			for _, st := range s.Else.Stmts {
				e.emitStmt(st)
			}
			e.indent--
		}
		e.ln("}")
	case *WhileStmt:
		e.ln("while (%s) {", e.emitExpr(s.Cond))
		e.indent++
		for _, st := range s.Body.Stmts {
			e.emitStmt(st)
		}
		e.indent--
		e.ln("}")
	case *UntilStmt:
		e.ln("while (!(%s)) {", e.emitExpr(s.Cond))
		e.indent++
		for _, st := range s.Body.Stmts {
			e.emitStmt(st)
		}
		e.indent--
		e.ln("}")
	case *ForRangeStmt:
		e.emitForRange(s)
	case *MatchStmt:
		e.emitMatch(s)
	case *TryCatchStmt:
		e.emitTryCatch(s)
	case *AssignStmt:
		e.ln("%s %s %s;", e.emitExpr(s.LHS), s.Op, e.emitExpr(s.Value))
	case *ExprStmt:
		ex := e.emitExpr(s.Expr)
		if ex != "" && ex != "0" {
			e.ln("%s;", ex)
		}
	case *PrintStmt:
		e.emitPrint(s)
	case *ExitStmt:
		e.ln("exit((int)(%s));", e.emitExpr(s.Code))
	case *BreakStmt:
		e.ln("break;")
	case *ContinueStmt:
		e.ln("continue;")
	case *AssertStmt:
		e.ln("if (!(%s)) { fprintf(stderr, \"Assertion failed: %%s\\n\", %s); exit(1); }", e.emitExpr(s.Cond), e.emitExpr(s.Msg))
	case *SpawnStmt:
		// spawn: fork + exec, or just run in background with system
		e.ln("/* spawn */ system(%s);", e.emitExpr(s.Call))
	case *DeferStmt: /* handled in emitBlockStmts */
	case *FnDecl:
		e.emitFnFull(s)
	case *Block:
		e.ln("{")
		e.indent++
		e.emitBlockStmts(s)
		e.indent--
		e.ln("}")
	case *PipeExpr:
		result := e.emitExpr(s)
		e.ln("%s;", result)
	}
}

func (e *Emitter) emitVarDecl(v *VarDecl) {
	typ := v.ResolvedType
	if typ == nil {
		typ = v.VarType
	}
	if typ == nil {
		typ = TypAny
	}
	prefix := ""
	if v.IsConst {
		prefix = "const "
	}
	if v.Init != nil {
		e.ln("%s%s = %s;", prefix, cTypeDecl(typ, v.Name), e.emitExpr(v.Init))
	} else {
		e.ln("%s%s;", prefix, cTypeDecl(typ, v.Name))
	}
}

func (e *Emitter) emitReturn(r *ReturnStmt) {
	if r.Value == nil {
		e.ln("return;")
	} else {
		e.ln("return %s;", e.emitExpr(r.Value))
	}
}

func (e *Emitter) emitIf(s *IfStmt) {
	e.ln("if (%s) {", e.emitExpr(s.Cond))
	e.indent++
	for _, st := range s.Then.Stmts {
		e.emitStmt(st)
	}
	e.indent--
	for _, el := range s.Elifs {
		e.ln("} else if (%s) {", e.emitExpr(el.Cond))
		e.indent++
		for _, st := range el.Body.Stmts {
			e.emitStmt(st)
		}
		e.indent--
	}
	if s.Else != nil {
		e.ln("} else {")
		e.indent++
		for _, st := range s.Else.Stmts {
			e.emitStmt(st)
		}
		e.indent--
	}
	e.ln("}")
}

func (e *Emitter) emitForRange(s *ForRangeStmt) {
	from := e.emitExpr(s.From)
	to := e.emitExpr(s.To)
	step := "1"
	if s.Step != nil {
		step = e.emitExpr(s.Step)
	}
	e.ln("for (long long %s = %s; %s < %s; %s += %s) {", s.Var, from, s.Var, to, s.Var, step)
	e.indent++
	for _, st := range s.Body.Stmts {
		e.emitStmt(st)
	}
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitMatch(s *MatchStmt) {
	// emit as if-else chain
	expr := e.emitExpr(s.Expr)
	tmp := e.tmp()
	e.ln("{ long long %s = (long long)(%s);", tmp, expr)
	e.indent++
	first := true
	for _, arm := range s.Arms {
		if arm.IsWild {
			if !first {
				e.sb.WriteString(" else ")
			} else {
				e.sb.WriteString(strings.Repeat("    ", e.indent))
			}
			e.sb.WriteString("{\n")
			e.indent++
			for _, st := range arm.Body.Stmts {
				e.emitStmt(st)
			}
			e.indent--
			e.sb.WriteString(strings.Repeat("    ", e.indent) + "}\n")
		} else {
			kw := "if"
			if !first {
				kw = "} else if"
			}
			cond := fmt.Sprintf("(%s == (long long)(%s))", tmp, e.emitExpr(arm.Pattern))
			if arm.Guard != nil {
				cond += " && (" + e.emitExpr(arm.Guard) + ")"
			}
			e.ln("%s (%s) {", kw, cond)
			e.indent++
			for _, st := range arm.Body.Stmts {
				e.emitStmt(st)
			}
			e.indent--
		}
		first = false
	}
	if !first {
		e.ln("}")
	}
	e.indent--
	e.ln("}")
}

func (e *Emitter) emitTryCatch(s *TryCatchStmt) {
	// try/catch maps to errno-based pattern
	e.ln("{ /* try */")
	e.indent++
	e.ln("errno = 0;")
	if s.Try != nil {
		for _, st := range s.Try.Stmts {
			e.emitStmt(st)
		}
	}
	e.indent--
	if s.Catch != nil {
		e.ln("if (errno != 0) { /* catch */")
		e.indent++
		if s.ErrVar != "" {
			e.ln("int %s = errno;", s.ErrVar)
		}
		for _, st := range s.Catch.Stmts {
			e.emitStmt(st)
		}
		e.indent--
		e.ln("}")
	}
	if s.Finally != nil {
		e.ln("{ /* finally */")
		e.indent++
		for _, st := range s.Finally.Stmts {
			e.emitStmt(st)
		}
		e.indent--
		e.ln("}")
	}
	e.ln("}")
}

func (e *Emitter) emitPrint(s *PrintStmt) {
	dest := "stdout"
	if s.ToStderr {
		dest = "stderr"
	}
	if len(s.Args) == 0 {
		if s.Newline {
			e.ln("fprintf(%s, \"\\n\");", dest)
		}
		return
	}
	var fmts, args []string
	for _, a := range s.Args {
		fmts = append(fmts, fmtFor(exprType(a)))
		args = append(args, e.emitExpr(a))
	}
	fmtStr := strings.Join(fmts, " ")
	if s.Newline {
		fmtStr += "\\n"
	}
	e.ln(`fprintf(%s, "%s", %s);`, dest, fmtStr, strings.Join(args, ", "))
}

// ── Expressions ───────────────────────────────────────────────────────────────

func (e *Emitter) emitExpr(n Node) string {
	if n == nil {
		return "0"
	}
	switch ex := n.(type) {
	case *IntLit:
		return fmt.Sprintf("%dLL", ex.Val)
	case *FloatLit:
		s := fmt.Sprintf("%g", ex.Val)
		if !strings.Contains(s, ".") && !strings.Contains(s, "e") {
			s += ".0"
		}
		return s
	case *BoolLit:
		if ex.Val {
			return "1"
		}
		return "0"
	case *StrLit:
		return cEscapeString(ex.Val)
	case *NilLit:
		return "NULL"
	case *Ident:
		return ex.Name
	case *BinExpr:
		return fmt.Sprintf("(%s %s %s)", e.emitExpr(ex.LHS), ex.Op, e.emitExpr(ex.RHS))
	case *UnaryExpr:
		return fmt.Sprintf("(%s%s)", ex.Op, e.emitExpr(ex.Operand))
	case *TernaryExpr:
		return fmt.Sprintf("((%s) ? (%s) : (%s))", e.emitExpr(ex.Cond), e.emitExpr(ex.Then), e.emitExpr(ex.Else))

	case *CallExpr:
		fn := e.emitExpr(ex.Func)
		var argStrs []string
		for _, a := range ex.Args {
			argStrs = append(argStrs, e.emitExpr(a))
		}
		return fmt.Sprintf("%s(%s)", fn, strings.Join(argStrs, ", "))

	case *BuiltinExpr:
		return e.emitBuiltin(ex)

	case *MethodCallExpr:
		recv := e.emitExpr(ex.Recv)
		recvType := exprType(ex.Recv)
		structName := ""
		if recvType != nil {
			if recvType.Kind == TyStruct {
				structName = recvType.Name
			}
			if recvType.Kind == TyRef && recvType.Elem != nil && recvType.Elem.Kind == TyStruct {
				structName = recvType.Elem.Name
			}
		}
		var argStrs []string
		argStrs = append(argStrs, recv)
		for _, a := range ex.Args {
			argStrs = append(argStrs, e.emitExpr(a))
		}
		if structName != "" {
			return fmt.Sprintf("%s_%s(%s)", structName, ex.Method, strings.Join(argStrs, ", "))
		}
		return fmt.Sprintf("%s(%s)", ex.Method, strings.Join(argStrs, ", "))

	case *PipeExpr:
		if len(ex.Steps) == 0 {
			return "0"
		}
		result := e.emitExpr(ex.Steps[0])
		for _, step := range ex.Steps[1:] {
			fnName := e.emitExpr(step)
			result = fmt.Sprintf("%s(%s)", fnName, result)
		}
		return result

	case *IndexExpr:
		return fmt.Sprintf("%s[%s]", e.emitExpr(ex.Obj), e.emitExpr(ex.Idx))
	case *FieldExpr:
		obj := e.emitExpr(ex.Obj)
		objType := exprType(ex.Obj)
		if objType != nil && objType.Kind == TyRef {
			return fmt.Sprintf("%s->%s", obj, ex.Field)
		}
		return fmt.Sprintf("%s.%s", obj, ex.Field)
	case *CastExpr:
		return fmt.Sprintf("((%s)(%s))", cType(ex.ToType), e.emitExpr(ex.Operand))
	case *AddrExpr:
		if ex.Deref {
			return fmt.Sprintf("(*%s)", e.emitExpr(ex.Operand))
		}
		return fmt.Sprintf("(&%s)", e.emitExpr(ex.Operand))

	case *StructInit:
		var parts []string
		for _, fi := range ex.Fields {
			parts = append(parts, fmt.Sprintf(".%s = %s", fi.Name, e.emitExpr(fi.Value)))
		}
		if ex.HeapAlloc {
			return fmt.Sprintf("((%s*)memcpy(malloc(sizeof(%s)), &(%s){%s}, sizeof(%s)))",
				ex.Name, ex.Name, ex.Name, strings.Join(parts, ", "), ex.Name)
		}
		return fmt.Sprintf("(%s){%s}", ex.Name, strings.Join(parts, ", "))

	case *ArrayLit:
		var parts []string
		for _, el := range ex.Elems {
			parts = append(parts, e.emitExpr(el))
		}
		return fmt.Sprintf("{%s}", strings.Join(parts, ", "))

	case *SizeofExpr:
		return fmt.Sprintf("(long long)sizeof(%s)", cType(ex.Of))

	case *TemplateStr:
		return e.emitTemplateStr(ex)

	case *CmdExpr:
		if ex.CaptureOutput {
			return fmt.Sprintf("__zx_capture_cmd(%s)", e.emitExpr(ex.Command))
		}
		return fmt.Sprintf("system(%s)", e.emitExpr(ex.Command))

	case *ReadFileExpr:
		return fmt.Sprintf("__zx_read_file(%s)", e.emitExpr(ex.Path))

	default:
		return "0"
	}
}

func (e *Emitter) emitBuiltin(b *BuiltinExpr) string {
	switch b.Name {
	case "len":
		if len(b.Args) == 1 {
			return fmt.Sprintf("(long long)strlen((const char*)(%s))", e.emitExpr(b.Args[0]))
		}
	case "input":
		prompt := "NULL"
		if len(b.Args) > 0 {
			prompt = e.emitExpr(b.Args[0])
		}
		return fmt.Sprintf("__zx_input(%s)", prompt)
	case "alloc":
		if len(b.Args) == 1 {
			return fmt.Sprintf("malloc((size_t)(%s))", e.emitExpr(b.Args[0]))
		}
	case "zalloc":
		if len(b.Args) == 2 {
			return fmt.Sprintf("calloc((size_t)(%s), (size_t)(%s))", e.emitExpr(b.Args[0]), e.emitExpr(b.Args[1]))
		}
	case "free":
		if len(b.Args) == 1 {
			return fmt.Sprintf("free(%s)", e.emitExpr(b.Args[0]))
		}
	case "system", "getenv":
		if len(b.Args) == 1 {
			return fmt.Sprintf("%s(%s)", b.Name, e.emitExpr(b.Args[0]))
		}
	case "str_eq":
		if len(b.Args) == 2 {
			return fmt.Sprintf("(strcmp(%s, %s) == 0)", e.emitExpr(b.Args[0]), e.emitExpr(b.Args[1]))
		}
	case "str_ne":
		if len(b.Args) == 2 {
			return fmt.Sprintf("(strcmp(%s, %s) != 0)", e.emitExpr(b.Args[0]), e.emitExpr(b.Args[1]))
		}
	case "is_nil":
		if len(b.Args) == 1 {
			return fmt.Sprintf("((void*)(%s) == NULL)", e.emitExpr(b.Args[0]))
		}
	case "not_nil":
		if len(b.Args) == 1 {
			return fmt.Sprintf("((void*)(%s) != NULL)", e.emitExpr(b.Args[0]))
		}
	case "to_int":
		if len(b.Args) == 1 {
			return fmt.Sprintf("((long long)(%s))", e.emitExpr(b.Args[0]))
		}
	case "to_float":
		if len(b.Args) == 1 {
			return fmt.Sprintf("((double)(%s))", e.emitExpr(b.Args[0]))
		}
	case "to_bool":
		if len(b.Args) == 1 {
			return fmt.Sprintf("(!!((%s)))", e.emitExpr(b.Args[0]))
		}
	case "to_char":
		if len(b.Args) == 1 {
			return fmt.Sprintf("((char)(%s))", e.emitExpr(b.Args[0]))
		}
	case "abs":
		if len(b.Args) == 1 {
			a := e.emitExpr(b.Args[0])
			return fmt.Sprintf("(((%s) < 0) ? -(%s) : (%s))", a, a, a)
		}
	case "min":
		if len(b.Args) == 2 {
			a := e.emitExpr(b.Args[0])
			bv := e.emitExpr(b.Args[1])
			return fmt.Sprintf("((%s) < (%s) ? (%s) : (%s))", a, bv, a, bv)
		}
	case "max":
		if len(b.Args) == 2 {
			a := e.emitExpr(b.Args[0])
			bv := e.emitExpr(b.Args[1])
			return fmt.Sprintf("((%s) > (%s) ? (%s) : (%s))", a, bv, a, bv)
		}
	case "clamp":
		if len(b.Args) == 3 {
			v := e.emitExpr(b.Args[0])
			lo := e.emitExpr(b.Args[1])
			hi := e.emitExpr(b.Args[2])
			return fmt.Sprintf("((%s) < (%s) ? (%s) : ((%s) > (%s) ? (%s) : (%s)))", v, lo, lo, v, hi, hi, v)
		}
	case "sizeof":
		if len(b.Args) == 1 {
			return fmt.Sprintf("(long long)sizeof(%s)", e.emitExpr(b.Args[0]))
		}
	}
	var argStrs []string
	for _, a := range b.Args {
		argStrs = append(argStrs, e.emitExpr(a))
	}
	return fmt.Sprintf("%s(%s)", b.Name, strings.Join(argStrs, ", "))
}

// emitTemplateStr: f"hello {name}!" → snprintf buffer
func (e *Emitter) emitTemplateStr(ts *TemplateStr) string {
	// build format string and args
	var fmtParts []string
	var args []string
	for _, part := range ts.Parts {
		if !part.IsExpr {
			// escape % in text
			escaped := strings.ReplaceAll(part.Text, "%", "%%")
			fmtParts = append(fmtParts, escaped)
		} else {
			t := exprType(part.Expr)
			fmtParts = append(fmtParts, fmtFor(t))
			args = append(args, e.emitExpr(part.Expr))
		}
	}
	fmtStr := strings.Join(fmtParts, "")
	//tmpName := e.tmp()
	// emit the snprintf as a comma expression using a static buffer
	argStr := ""
	if len(args) > 0 {
		argStr = ", " + strings.Join(args, ", ")
	}
	return fmt.Sprintf("(snprintf(__zx_input_buf, sizeof(__zx_input_buf), \"%s\"%s), __zx_input_buf)", fmtStr, argStr)
}

// ── C type helpers ────────────────────────────────────────────────────────────

func cType(t *ZXType) string {
	if t == nil {
		return "long long"
	}
	switch t.Kind {
	case TyInt:
		return "long long"
	case TyFloat:
		return "double"
	case TyBool:
		return "int"
	case TyStr:
		return "const char*"
	case TyChar:
		return "char"
	case TyVoid:
		return "void"
	case TyAny:
		return "long long"
	case TyRef:
		if t.Elem != nil {
			return cType(t.Elem) + "*"
		}
		return "void*"
	case TyArray:
		if t.Elem != nil {
			return cType(t.Elem)
		}
		return "void*"
	case TySlice:
		if t.Elem != nil {
			return cType(t.Elem) + "*"
		}
		return "void*"
	case TyStruct:
		return t.Name
	default:
		return "long long"
	}
}

func cTypeDecl(t *ZXType, name string) string {
	if t != nil && t.Kind == TyArray {
		sz := ""
		if t.ArrSize > 0 {
			sz = fmt.Sprintf("%d", t.ArrSize)
		}
		return fmt.Sprintf("%s %s[%s]", cType(t.Elem), name, sz)
	}
	return fmt.Sprintf("%s %s", cType(t), name)
}

func methodParamStr(m *MethodDecl) string {
	recvTyp := m.RecvType
	if m.RecvRef {
		recvTyp = m.RecvType + "*"
	}
	parts := []string{recvTyp + " " + m.RecvName}
	for _, p := range m.Params {
		parts = append(parts, cTypeDecl(p.Type, p.Name))
	}
	if m.Variadic {
		parts = append(parts, "...")
	}
	return strings.Join(parts, ", ")
}

func buildParamStr(params []Param, variadic bool) string {
	if len(params) == 0 {
		if variadic {
			return "..."
		}
		return "void"
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = cTypeDecl(p.Type, p.Name)
	}
	if variadic {
		parts = append(parts, "...")
	}
	return strings.Join(parts, ", ")
}

func fmtFor(t *ZXType) string {
	if t == nil {
		return "%s"
	}
	switch t.Kind {
	case TyInt:
		return "%lld"
	case TyFloat:
		return "%g"
	case TyBool:
		return "%d"
	case TyStr:
		return "%s"
	case TyChar:
		return "%c"
	case TyRef:
		return "%p"
	default:
		return "%s"
	}
}

func exprType(n Node) *ZXType {
	switch e := n.(type) {
	case *IntLit:
		return TypInt
	case *FloatLit:
		return TypFloat
	case *BoolLit:
		return TypBool
	case *StrLit:
		return TypStr
	case *Ident:
		return e.Typ
	case *BinExpr:
		return e.Typ
	case *UnaryExpr:
		return e.Typ
	case *CallExpr:
		return e.Typ
	case *MethodCallExpr:
		return e.Typ
	case *BuiltinExpr:
		return e.Typ
	case *CastExpr:
		return e.Typ
	case *AddrExpr:
		return e.Typ
	case *FieldExpr:
		return e.Typ
	case *IndexExpr:
		return e.Typ
	case *ArrayLit:
		return e.Typ
	case *PipeExpr:
		return e.Typ
	case *TemplateStr:
		return TypStr
	case *CmdExpr:
		return TypStr
	case *ReadFileExpr:
		return TypStr
	case *TernaryExpr:
		return e.Typ
	case *SizeofExpr:
		return TypInt
	default:
		return TypAny
	}
}

func cEscapeString(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		case '\r':
			sb.WriteString(`\r`)
		case 0:
			sb.WriteString(`\0`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
