package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ─────────────────────────────────────────────────────────────────────────────
//  Test discovery — collect all @test functions from a Program
// ─────────────────────────────────────────────────────────────────────────────

// CollectTests gathers all @test-annotated functions from the whole program,
// including those inside mod { mod { ... } } blocks.
func CollectTests(prog *Program) []*TestDecl {
	var tests []*TestDecl

	// top-level @test functions
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok {
			if fn.HasAnnotation(AnnTest) {
				tests = append(tests, buildTestDecl(fn, ""))
			}
		}
	}

	// inside mod blocks (recursively)
	for _, mb := range prog.ModBlocks {
		tests = append(tests, collectModTests(mb)...)
	}

	return tests
}

func collectModTests(mb *ModBlock) []*TestDecl {
	var tests []*TestDecl
	tests = append(tests, mb.Tests...)
	for _, nested := range mb.Mods {
		tests = append(tests, collectModTests(nested)...)
	}
	return tests
}

// ─────────────────────────────────────────────────────────────────────────────
//  Test Code Generation
//  Each @test function is called from a generated __zx_run_tests() function.
//  The runner prints results with color and counts pass/fail/skip.
// ─────────────────────────────────────────────────────────────────────────────

// EmitTestRunner generates a main() that runs all discovered tests
func EmitTestRunner(prog *Program, tests []*TestDecl) string {
	e := &Emitter{}

	// Emit the program normally (without a main())
	e.ln("/* generated by zxc test runner */")
	e.ln("#include <stdio.h>")
	e.ln("#include <stdlib.h>")
	e.ln("#include <string.h>")
	e.ln("#include <math.h>")
	e.ln("#include <stdbool.h>")
	e.ln("#include <setjmp.h>")
	e.ln("#include <signal.h>")
	e.ln("#include <errno.h>")
	e.ln("")

	// std module headers
	for _, h := range prog.StdHeaders() {
		e.ln("#include <%s>", h)
	}
	for _, h := range prog.StdHelpers() {
		e.raw(h)
	}

	// input helper
	e.ln("static char __zx_input_buf[4096];")
	e.ln("static const char* __zx_input(const char* prompt) {")
	e.indent++
	e.ln("if (prompt) { fputs(prompt, stdout); fflush(stdout); }")
	e.ln("if (!fgets(__zx_input_buf, sizeof(__zx_input_buf), stdin)) return \"\";")
	e.ln("size_t __l = strlen(__zx_input_buf);")
	e.ln("if (__l > 0 && __zx_input_buf[__l-1] == '\\n') __zx_input_buf[__l-1] = '\\0';")
	e.ln("return __zx_input_buf;")
	e.indent--
	e.ln("}")
	e.ln("")
	e.ln("static char __zx_cmd_buf[65536];")
	e.ln("static const char* __zx_capture_cmd(const char* cmd) {")
	e.indent++
	e.ln("FILE* __p = popen(cmd, \"r\");")
	e.ln("if (!__p) { __zx_cmd_buf[0]='\\0'; return __zx_cmd_buf; }")
	e.ln("size_t __tot = 0; char __tmp[1024];")
	e.ln("while (fgets(__tmp, sizeof(__tmp), __p) && __tot + strlen(__tmp) < sizeof(__zx_cmd_buf)-1) {")
	e.indent++
	e.ln("memcpy(__zx_cmd_buf + __tot, __tmp, strlen(__tmp)); __tot += strlen(__tmp);")
	e.indent--
	e.ln("}")
	e.ln("__zx_cmd_buf[__tot] = '\\0'; pclose(__p); return __zx_cmd_buf;")
	e.indent--
	e.ln("}")
	e.ln("")

	// structs
	for _, s := range prog.Structs {
		e.emitStruct(s)
	}
	for _, mb := range prog.ModBlocks {
		emitModStructs(e, mb)
	}

	// externs
	for _, ext := range prog.Externs {
		if !knownCFuncs[ext.Name] {
			e.ln("extern %s %s(%s);", cType(ext.RetType), ext.Name, buildParamStr(ext.Params, ext.Variadic))
		}
	}

	// forward declarations for all user fns + test fns
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok && fn.Name != "main" {
			e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
		}
	}
	for _, mb := range prog.ModBlocks {
		emitModFnProtos(e, mb)
	}
	for _, m := range prog.Methods {
		e.ln("%s %s(%s);", cType(m.RetType), m.CName(), methodParamStr(m))
	}
	e.ln("")

	// user fn bodies (no main)
	for _, stmt := range prog.TopStmts {
		if fn, ok := stmt.(*FnDecl); ok && fn.Name != "main" {
			e.emitFnFull(fn)
			e.ln("")
		}
	}
	for _, mb := range prog.ModBlocks {
		emitModFnBodies(e, mb)
	}
	for _, m := range prog.Methods {
		e.emitMethodFull(m)
		e.ln("")
	}

	// test color macros
	e.ln("/* ── ZX test runner ─────────────────────────────────────────── */")
	e.ln("#define ZX_PASS  \"\\033[1m\\033[92m PASS\\033[0m\"")
	e.ln("#define ZX_FAIL  \"\\033[1m\\033[91m FAIL\\033[0m\"")
	e.ln("#define ZX_SKIP  \"\\033[1m\\033[93m SKIP\\033[0m\"")
	e.ln("#define ZX_INFO  \"\\033[96m\"")
	e.ln("#define ZX_RESET \"\\033[0m\"")
	e.ln("")

	// generate test runner main
	e.ln("int main(int argc, char **argv) {")
	e.indent++
	e.ln("int __pass = 0, __fail = 0, __skip = 0;")
	e.ln("(void)argc; (void)argv;")
	e.ln("fprintf(stderr, \"\\n\\033[1m\\033[96m ZX Test Runner\\033[0m\\n\");")
	e.ln("fprintf(stderr, \"────────────────────────────────────\\n\");")

	for _, td := range tests {
		emitTestCall(e, td)
	}

	e.ln("")
	e.ln("fprintf(stderr, \"────────────────────────────────────\\n\");")
	e.ln("fprintf(stderr, \"\\033[1mResults:\\033[0m  \");")
	e.ln("fprintf(stderr, ZX_PASS \" %d   \", __pass);")
	e.ln("fprintf(stderr, ZX_FAIL \" %d   \", __fail);")
	e.ln("fprintf(stderr, ZX_SKIP \" %d\\n\\n\", __skip);")
	e.ln("return __fail > 0 ? 1 : 0;")
	e.indent--
	e.ln("}")

	return e.sb.String()
}

// emitTestCall emits a single test invocation in the runner main()
func emitTestCall(e *Emitter, td *TestDecl) {
	fn := td.Fn
	displayName := fn.Name
	if td.ModPath != "" {
		displayName = td.ModPath + "::" + fn.Name
	}

	if td.Ignored {
		e.ln("fprintf(stderr, ZX_SKIP \" %%s\\n\", %q);", displayName)
		e.ln("__skip++;")
		return
	}

	// Build argument list from @args
	argStr := buildTestArgs(fn, td)

	// Check if function has a return value to display/check
	hasReturn := fn.RetType != nil && fn.RetType.Kind != TyVoid
	retDecl := ""
	retCheck := ""
	if hasReturn {
		retDecl = fmt.Sprintf("%s __ret = ", cType(fn.RetType))
		if td.Expected != "" {
			retCheck = fmt.Sprintf(
				"if ((long long)__ret != %s) { fprintf(stderr, ZX_FAIL \" %%s  (expected %s got %%lld)\\n\", \"%s\", (long long)__ret); __fail++; } else { fprintf(stderr, ZX_PASS \" %%s → %%lld\\n\", \"%s\", (long long)__ret); __pass++; }",
				td.Expected, td.Expected, displayName, displayName)
		} else {
			retCheck = fmt.Sprintf(
				"fprintf(stderr, ZX_PASS \" %%s → \"); fprintf(stderr, \"%s\\n\", __ret); __pass++;",
				fmtFor(fn.RetType))
		}
	} else {
		retCheck = fmt.Sprintf(
			"fprintf(stderr, ZX_PASS \" %%s\\n\", \"%s\"); __pass++;",
			displayName)
	}

	e.ln("/* test: %s */", displayName)
	e.ln("{")
	e.indent++
	e.ln("errno = 0;")
	if hasReturn {
		e.ln("%s%s(%s);", retDecl, fn.Name, argStr)
		e.ln("if (errno != 0) {")
		e.indent++
		e.ln("fprintf(stderr, ZX_FAIL \" %s  (errno=%%d: %%s)\\n\", errno, strerror(errno));", displayName)
		e.ln("__fail++;")
		e.indent--
		e.ln("} else {")
		e.indent++
		e.ln("%s", retCheck)
		e.indent--
		e.ln("}")
	} else {
		e.ln("%s(%s);", fn.Name, argStr)
		e.ln("if (errno != 0) {")
		e.indent++
		e.ln("fprintf(stderr, ZX_FAIL \" %s  (errno=%%d: %%s)\\n\", errno, strerror(errno));", displayName)
		e.ln("__fail++;")
		e.indent--
		e.ln("} else {")
		e.indent++
		e.ln("%s", retCheck)
		e.indent--
		e.ln("}")
	}
	e.indent--
	e.ln("}")
}

// buildTestArgs converts @args={"n":42,"s":"hello"} into a C argument string
func buildTestArgs(fn *FnDecl, td *TestDecl) string {
	if len(fn.Params) == 0 {
		return ""
	}
	if td.Args == nil {
		// no @args provided — emit zeros/empty for each param
		parts := make([]string, len(fn.Params))
		for i, p := range fn.Params {
			switch {
			case p.Type == nil || p.Type.Kind == TyAny || p.Type.Kind == TyInt:
				parts[i] = "0LL"
			case p.Type.Kind == TyFloat:
				parts[i] = "0.0"
			case p.Type.Kind == TyStr:
				parts[i] = `""`
			case p.Type.Kind == TyBool:
				parts[i] = "0"
			default:
				parts[i] = "0LL"
			}
		}
		return strings.Join(parts, ", ")
	}
	parts := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		val, ok := td.Args[p.Name]
		if !ok {
			// try positional by index
			val = td.Args[fmt.Sprintf("%d", i)]
		}
		if val == "" {
			val = "0"
		}
		// format based on type
		if p.Type != nil && p.Type.Kind == TyStr {
			parts[i] = fmt.Sprintf(`"%s"`, val)
		} else if p.Type != nil && p.Type.Kind == TyFloat {
			parts[i] = val
		} else {
			parts[i] = val + "LL"
		}
	}
	return strings.Join(parts, ", ")
}

// ── mod block helpers for test code gen ───────────────────────────────────────

func emitModStructs(e *Emitter, mb *ModBlock) {
	for _, s := range mb.Structs {
		e.emitStruct(s)
	}
	for _, nested := range mb.Mods {
		emitModStructs(e, nested)
	}
}

func emitModFnProtos(e *Emitter, mb *ModBlock) {
	for _, fn := range mb.Fns {
		e.ln("%s %s(%s);", cType(fn.RetType), fn.Name, buildParamStr(fn.Params, fn.Variadic))
	}
	for _, td := range mb.Tests {
		e.ln("%s %s(%s);", cType(td.Fn.RetType), td.Fn.Name, buildParamStr(td.Fn.Params, td.Fn.Variadic))
	}
	for _, nested := range mb.Mods {
		emitModFnProtos(e, nested)
	}
}

func emitModFnBodies(e *Emitter, mb *ModBlock) {
	for _, fn := range mb.Fns {
		e.emitFnFull(fn)
		e.ln("")
	}
	for _, td := range mb.Tests {
		e.emitFnFull(td.Fn)
		e.ln("")
	}
	for _, nested := range mb.Mods {
		emitModFnBodies(e, nested)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
//  RunTests — compile test runner and execute it
// ─────────────────────────────────────────────────────────────────────────────

func RunTests(prog *Program, sourceFile string, verbose bool) {
	tests := CollectTests(prog)

	if len(tests) == 0 {
		fmt.Printf("\n%s%s⚠%s  No @test functions found in %s\n",
			colorBold, colorYellow, colorReset, sourceFile)
		fmt.Printf("  Add @test before a fn to make it a test:\n\n")
		fmt.Printf("    %s@test%s\n    fn my_test() {\n        // your test code here\n    }\n\n",
			colorGreen, colorReset)
		return
	}

	fmt.Printf("\n%s%s Found %d test(s) in %s%s\n",
		colorBold, colorCyan, len(tests), sourceFile, colorReset)

	cCode := EmitTestRunner(prog, tests)
	if verbose {
		printCSource(cCode)
	}

	tmpC, err := os.CreateTemp("", "zx_test_*.c")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%szxc: cannot create temp test file: %v%s\n", colorRed, err, colorReset)
		os.Exit(1)
	}
	defer os.Remove(tmpC.Name())
	tmpC.WriteString(cCode)
	tmpC.Close()

	outBin := filepath.Join(os.TempDir(), "zx_test_runner")
	defer os.Remove(outBin)

	gccArgs := []string{
		"-x", "c", tmpC.Name(), "-o", outBin,
		"-lm", "-Wall",
		"-Wno-unused-variable", "-Wno-unused-function",
		"-Wno-implicit-function-declaration",
	}
	gccOut, err := exec.Command("gcc", gccArgs...).CombinedOutput()
	if err != nil {
		fmt.Fprintf(os.Stderr, "\n%s%s✖ Test compile error:%s\n%s%s%s\n",
			colorBold, colorRed, colorReset,
			colorDim, string(gccOut), colorReset)
		fmt.Fprintf(os.Stderr, "\n%s💡 run 'zxc emit %s' to inspect the generated C%s\n\n",
			colorYellow, sourceFile, colorReset)
		os.Exit(1)
	}

	runCmd := exec.Command(outBin)
	runCmd.Stdin = os.Stdin
	runCmd.Stdout = os.Stdout
	runCmd.Stderr = os.Stderr
	err = runCmd.Run()
	if exitErr, ok := err.(*exec.ExitError); ok {
		os.Exit(exitErr.ExitCode())
	}
}

// printCSource is used by RunTests (defined here to avoid import cycle)
func printCSource(code string) {
	lines := strings.Split(code, "\n")
	fmt.Printf("\n%s%s── generated C (%d lines) ──────────────────────%s\n",
		colorBold, colorCyan, len(lines), colorReset)
	for i, l := range lines {
		fmt.Printf("%s%4d%s  %s\n", colorDim, i+1, colorReset, l)
	}
	fmt.Printf("%s%s────────────────────────────────────────────%s\n\n",
		colorBold, colorCyan, colorReset)
}
